import React from 'react';
import { X, MessageSquare, Phone, Instagram, ArrowUpRight, Headphones } from 'lucide-react';
import { useDialog } from '../hooks/useDialog';
interface Props {isOpen:boolean;onClose:()=>void;}
export const SocialModal=({isOpen,onClose}:Props)=>{
 const ref=useDialog(isOpen,onClose);if(!isOpen)return null;
 const links=[{name:'Comunidade no Discord',subtitle:'Dúvidas, novidades e próximos jogos',url:import.meta.env.VITE_DISCORD_URL||'https://discord.gg/abravanel',Icon:MessageSquare},{name:'WhatsApp',subtitle:'Converse com o atendimento',url:import.meta.env.VITE_WHATSAPP_URL,Icon:Phone},{name:'Instagram',subtitle:'Acompanhe a Abravanel',url:import.meta.env.VITE_INSTAGRAM_URL,Icon:Instagram}].filter(l=>{try{return new URL(l.url).protocol==='https:';}catch{return false;}});
 return <div ref={ref} role="dialog" aria-modal="true" aria-label="Comunidade e suporte" tabIndex={-1} className="shop-dialog-backdrop" onClick={e=>{if(e.currentTarget===e.target)onClose();}}><div className="checkout-panel"><div className="checkout-header"><span><Headphones size={19}/><h2>Vamos conversar?</h2></span><button className="icon-button" aria-label="Fechar janela" onClick={onClose}><X size={21}/></button></div><div className="p-6"><p className="mb-6 text-xs leading-6 text-slate-400">Um bom jogo fica ainda melhor com a companhia certa. Entre na comunidade para tirar dúvidas e acompanhar as novidades.</p><div className="space-y-3">{links.map(({name,subtitle,url,Icon})=><a key={name} href={url} target="_blank" rel="noopener noreferrer" className="flex items-center gap-4 rounded-xl border border-emerald-200/10 bg-emerald-100/5 p-4 hover:border-emerald-200/40 transition-colors"><Icon size={24} className="text-emerald-300"/><span className="flex-1"><strong className="block text-sm font-semibold">{name}</strong><small className="block mt-1 text-[10px] text-slate-400">{subtitle}</small></span><ArrowUpRight size={17} className="text-emerald-200"/></a>)}</div></div></div></div>;
};
